object FrmFormBase: TFrmFormBase
  Left = 0
  Top = 0
  Width = 543
  Height = 281
  AutoScroll = True
  Caption = 'FrmFormBase'
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  FormStyle = fsMDIChild
  OldCreateOrder = False
  Visible = True
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
end
